#!/stage1/busybox sh
_PATH="$PATH"
export PATH=/stage1

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

busybox mount -t ext2 /dev/block/mmcblk0p9 /ramdisk
busybox mount -t ext2 /dev/block/mmcblk0p17 /recovery

load_image=/stage1/boot.cpio

if busybox grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot
	load_image=/recovery/recovery.cpio
fi

if test -f ${load_image} ; then
	busybox cpio -i < ${load_image}
fi

if test -f ${load_image}.gz ; then
	busybox zcat ${load_image}.gz | busybox cpio -i -u
fi

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
busybox rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init
