#!/stage1/busybox sh
_PATH="$PATH"
export PATH=/stage1

cd /
date >>boot.txt
exec >>boot.txt 2>&1
rm init
mount -t proc proc /proc
mount -t sysfs sysfs /sys

echo 200000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 800000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

mount -t ext4 /dev/block/mmcblk0p9 /ramdisk

if ! grep -q bootmode=2 /proc/cmdline ; then
if ! grep -q lpm_boot=1 /proc/cmdline ; then
	if ! grep no /ramdisk/pllddr_oc_freq ; then
	PATH=/stage1 sh /ramdisk/pllddr_oc.sh $(cat /ramdisk/pllddr_oc_freq)
	fi
fi
fi

load_image=/stage1/boot.cpio

if grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot
	load_image=/stage1/recovery.cpio
fi

cpio -i < ${load_image}

umount /sys
umount /proc
date >>boot.txt
rm -fr /stage1
export PATH="${_PATH}"
exec /init
