#!/stage1/busybox sh
_PATH="$PATH"
export PATH=/stage1

busybox cd /
busybox date >>boot.txt
exec >>boot.txt 2>&1
busybox rm init
busybox mount -t proc proc /proc
busybox mount -t sysfs sysfs /sys

busybox echo 150000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
busybox echo 800000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq

busybox mount -t ext2 /dev/block/mmcblk0p9 /ramdisk

load_image=/stage1/boot.cpio

if busybox grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot
	load_image=/stage1/recovery.cpio
fi

busybox cpio -i < ${load_image}

busybox umount /sys
busybox umount /proc
busybox date >>boot.txt
busybox rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init
